### ISSUE TITLE
Windows Virtual Desktop - deployment problem

### ISSUE THREAD

**Issue by aurelienb1** [Azure/RDS-Templates#190]
In my comprehension :

The first part is deploying infrasctructure in Azure (that make availability set with networks, machines, disks ....), this step is good.

The second part is deploying Managament Tool (to have a SAAS to control infrastructure), in my case i get an error in this part. Through GitHub i deploy in Azure the template and i get a conflit error (see picture), but a web page "Your app service is up and runing") but i don't have managment tool web service.

![DeploymentFailed](https://user-images.githubusercontent.com/51001741/61215304-79e97300-a6d8-11e9-859b-7dd1c82faec2.PNG)

There is an error in template ?

Thank you

**Comment by chield** [comment]
Any news on this issue? Need to get this up and running for a POC...

**Comment by aurelienb1** [comment]
Hi,
You can try and post a reply if you get the same error message.
Thank you

**Comment by Rachaelgomer** [comment]
I got this same error, and it was due to the credentials you enter when deploying the Web App. While my user was a Global Admin (and an RDS Tenant Owner), they weren't a 'Contributor' at the Subscription level. So went into that particular subscription and assigned the role of contributor, and then this deploy template started working.

Hope this helps!

**Comment by ccharras** [comment]
Thanks Rachael, had this issue and fixed it as suggested by adding Contributor role

**Comment by aurelienb1** [comment]
Thanks Rachel, it's done and it works !!!

**Comment by viswanadham-k** [comment]
Hi Aurelienb1,
Can you please close this github issue.
