### ISSUE TITLE
x.xxxxx@xxxxxx.org.uk emails not accepted

### ISSUE THREAD

**Issue by hobn1354** [Azure/RDS-Templates#233]
Our organisation uses 'f.surname@hobnob.org.uk' email format. For example, John Smith's email would be 'j.smith@hobnob.org.uk', and Joe Blogg's would be 'j.bloggs@hobnob.org.uk'.

Having only ONE letter before the first dot, followed by the surname and then an .org.uk domain is not accepted...

**Comment by ChristianMontoya** [comment]
@hobn1354 : Is this on the GitHub ARM template? Or the marketplace? I would recommend running the [Create and Provision host pool](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool), since there is no specific validation and this should work.

**Comment by nakranimohit0** [comment]
Closing this out as there is no response. Please re-open if its still an issue.
