### ISSUE TITLE
Update an existing WVD host pool error 

### ISSUE THREAD

**Issue by samuelkajindrancts** [Azure/RDS-Templates#238]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"DSC Configuration 'FirstSessionHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource failed to execute Set-TargetResource functionality with error message: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by viswanadham-k** [comment]
Hi,
Do you have access to the VM? Can you check this log file: C:\Windows\Temp\ScriptLog.log  and please share with me.

**Comment by lintFan** [comment]
@samuelkajindrancts There were some changes made to the master branch of this repository on Jan 26, 2020 7:46 PM PT (in #308 ) which updates the version of the [WVD Powershell](https://docs.microsoft.com/en-us/powershell/windows-virtual-desktop/overview) module it uses to the latest version 1.0.1534.2001 which has some fixes around service principles and also adds support for a standard single-tenant service principal, so it may be worth trying the deployment again. You will need to deploy from this repository in order to use the ARM Template with these changes because they aren't in the Azure marketplace yet.

**Comment by nakranimohit0** [comment]
Closing out this issue as a duplicate to #321 
Please re-open if its diff.
