### ISSUE TITLE
"code": "VMExtensionProvisioningError",

### ISSUE THREAD

**Issue by lelandvelasco** [Azure/RDS-Templates#240]
Made some changes on the vm name on the main template. I'm not if this complicates..I got this error during rollout.

New-AzResourceGroupDeployment : 11:14:56 AM - Resource Microsoft.Compute/virtualMachines/extensions 'weuwvdp-0/dscextension' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'FirstSessionHost' completed with error(s). Following are the first few: PowerShell 
DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: One or more errors occurred.  The SendConfigurationApply function did not succeed.\"."
      }
    ]
  }

**Comment by viswanadham-k** [comment]
Hi,
Do you have access to the VM? Can you check this log file: C:\Windows\Temp\ScriptLog.log and please share with me.

**Comment by lintFan** [comment]
@lelandvelasco There were some changes made to the master branch of this repository on Jan 26, 2020 7:46 PM PT (in #308 ) that should improve the error messages around the authentication in the case where it used to just say "One or more errors occurred." which is what your last message contains. If you would like to try deploying using these latest ARM template changes you will need to deploy from the this repository because they are not on the Azure marketplace yet.

**Comment by ChristianMontoya** [comment]
@lelandvelasco : will close out for the time being. Please re-open or re-tag me if we need to continue addressing this.
