### ISSUE TITLE
Management tool failing on automation job 

### ISSUE THREAD

**Issue by tigerdeccan** [Azure/RDS-Templates#293]
Automation job failing with below error . This runbook needs updating to Az modules . its good time to do it given support for AzureRM has ended. 

Add-AzureRmAccount : unknown_user_type: Unknown User Type At line:38 char:1 + Add-AzureRmAccount -Environment 'AzureCloud' -Credential $Credentials + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Connect-AzureRmAccount], AadAuthenticationFailedException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

**Comment by viswanadham-k** [comment]
Hi,
Thank you for deploying management ux tool, i hope you got this error due to the credentials you enter when deploying the Web App, your credentials weren't a 'Contributor' at the Subscription level. So please check your credentials have "Contributor" access at subscription. If not please assign the role of contributor to your credentials and then run the deployment again, but use a new name as the Application Name.

**Comment by ChristianMontoya** [comment]
@tigerdeccan : We just updated to the Az modules with PR #320 . Can you please try re-deploying? As @viswanadham-k mentioned is true if you want to deploy with **isServicePrincipal** = false. If you want to deploy through a service principal / PowerShell, please see this doc: https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell

**Comment by ChristianMontoya** [comment]
@tigerdeccan : Closing for now. Please re-open if you need to.
