### ISSUE TITLE
Deployment Fails with terminal provisioning state 'Failed'

### ISSUE THREAD

**Issue by kwinegar** [Azure/RDS-Templates#373]
I was performing this as a subscription owner

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

**Comment by WLabat** [comment]
Facing same issue

**Comment by ranand12** [comment]
+ 1 - Facing same issue. Tried it several times with different permutations - I also tried with a unique app name still no luck

**Comment by madhensley** [comment]
Also facing the same issue. Tried multiple times with different users, settings etc. no luck.
```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"DSC Configuration 'RegisterSessionHost' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: Cannot find any service with service name 'RDAgentBootLoader'.  The SendConfigurationApply function did not succeed.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
            }
        ]
    }
}
```

**Comment by lintFan** [comment]
Please also reply back with the following:
1. Are you running the [Create  ](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool) or the [Update ](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool) template?
2. If you are using the create template have you tried the [Azure Marketplace template](https://ms.portal.azure.com/#create/rds.wvd-provision-host-poolpreview) and did it work for you?
3. What OS are you using for the VMs?
4. What approximate date and time did the error occur? Were you using the latest code from the master branch of this repository at that time?

@kwinegar  @WLabat  @ranand12 The error
`The resource operation completed with terminal provisioning state 'Failed'`
can be caused by many different things. Please post the whole error message including the "details" field; you can find the full error message by looking at your deployments in the Azure Portal and clicking the "(Error details)" link and then clicking the "Raw Error" tab. For example madhensley already posted the full error details they got.

**Comment by lintFan** [comment]
If you still have a VM where your error occurred please copy the file C:\Windows\Temp\ScriptLog.log from it as it contains logs from the template and may be handy for further troubleshooting.

@madhensley  Please create a new github issue for the error you are getting and post a link to it here. There reason I want a new issue is because your issue is likely different from the other people's issues. In your new issue please follow [these instructions](https://docs.microsoft.com/en-us/azure/virtual-desktop/troubleshoot-vm-configuration#windows-virtual-desktop-agent-and-windows-virtual-desktop-boot-loader-are-not-installed) to check for the presence of Windows Virtual Desktop Agent and Windows Virtual Desktop Agent Boot Loader and post what you find. Also post the contents of C:\Windows\Temp\ScriptLog.log starting with the line "AgentInstaller is".

**Comment by madhensley** [comment]
@lintFan seems the issue is fixed for me. Deployed two separate test machines using the "Create and provision WVD host pool" template and the machines got created.

regards Hens

**Comment by kwinegar** [comment]
I was able to successfully deploy using powershell as outlined

https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell 

Basically, manually, everything worked, with the exception apparently app name and therefore the website whose URL is created from the app has to be a globally unique name.

**Comment by jcwl2021** [comment]
Hi I am trying to create a custom deployment for a MS Team App template on Azure portal.  My deployment failed. 

Error message: The resource operation completed with terminal provisioning state 'Failed'.

Raw Error:
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

What do I do from here? What do I need to change before redployment?

**Comment by ozdemiremrah81** [comment]
Same issue with [OpenShift Origin Deployment Template](https://github.com/Microsoft/openshift-origin)

**Comment by noorsyyad** [comment]
> I was able to successfully deploy using powershell as outlined
> 
> https://docs.microsoft.com/en-us/azure/virtual-desktop/manage-resources-using-ui-powershell
> 
> Basically, manually, everything worked, with the exception apparently app name and therefore the website whose URL is created from the app has to be a globally unique name.

link here doesn't anymore, what did you rename in deployment template to make app name globally unique

**Comment by lintFan** [comment]
@jcwl2021 and @noorsyyad please open a new issue so that they can be tracked. Please be sure to include a link to the specific ARM template you are running.

@ozdemiremrah81 This repository is specific to ARM templates for WVD, so I can't help you with general ARM template errors. This page has some general advice for troubleshooting deployment errors https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-troubleshoot#troubleshoot-the-deployment-error .

@noorsyyad  This appears to be the new URL for the link you quoted https://docs.microsoft.com/en-us/azure/virtual-desktop/virtual-desktop-fall-2019/manage-resources-using-ui-powershell
