### ISSUE TITLE
"Unable to check status of firewall" - dscextension error

### ISSUE THREAD

**Issue by Xandven** [Azure/RDS-Templates#435]
Default display language other English in the user profile that adds VMs to the domain causes the dscextension resource to fail when deploying the "wvd-templates/Create and provision WVD host pool" template using Windows 10 Enterprise Multi Session hosts. In my case I had Norwegian as the default display language. The failing powershell function is Set-WSManQuickConfig.

Errormessage: 
"code": "VMExtensionProvisioningError", "message": "VM has reported a failure when processing extension 'dscextension'. Error message: \"The DSC Extension failed to execute: <f:WSManFault xmlns:f=\"http://schemas.microsoft.com/wbem/wsman/1/wsmanfault\" Code=\"2\" Machine=\"localhost\"><f:Message><f:ProviderFault provider=\"Config provider\" path=\"%systemroot%\\system32\\WsmSvc.dll\"><f:WSManFault xmlns:f=\"http://schemas.microsoft.com/wbem/wsman/1/wsmanfault\" Code=\"2\" Machine=\"wvdhost-0.xxx.yyy\"><f:Message>Kan ikke kontrollere status for brannmuren. </f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>.\r\nMore information about the failure can be found in the logs located under 'C:\\WindowsAzure\\Logs\\Plugins\\Microsoft.Powershell.DSC\\2.80.0.0' on the VM.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "

I have reproduced this in a test environment and verified that changing the display language to English fixes the problem.

Hopefully this will help anyone else that happens to stumble upon this error.

**Comment by AzureAzim** [comment]
I am encountering this issue as well, should we set localization after host pool deployment?

**Comment by Xandven** [comment]
Hi, please note the workaround I mentioned above. 

It is the display language of the user that is used to join the hosts to the domain that cause the problem. The dscextension  is installed in the context of this user. To fix the problem sign in with the mentioned domain user and change its default display language to English. I have deployed 100s of hosts post this fixed without any problems.

Doing the localization after host pool deployment would be a real pain, and the recommendation is actually to have the all the correct language packs installed in the golden image before you deploy the pool. 

This should be classified as a bug and fixed.

**Comment by AzureAzim** [comment]
IIRC, adding language packs to a golden image causes sysprep to fail now because the packs install as UWPs. While it is a workaround, it is certainly not inclusive to non English customers

https://docs.microsoft.com/en-us/troubleshoot/windows-client/deployment/sysprep-fails-remove-or-update-store-apps

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lintFan** [comment]
@Xandven and @AzureAzim thank you for reporting this. Please open an Azure support case for this as investigating it will require collecting logs etc, please choose the following when creating the support ticket so that it gets routed to the DSC Extension team:
Issue type: Technical 
Service "Virtual Machine running Windows"
Problem Type "VM Extensions not operating correctly"
Problem subtype: "Azure Desired State Configuration (DSC) extension issue"

Please let me know here if you have any problems getting support for this.
