### ISSUE TITLE
Host disapear from HostPool

### ISSUE THREAD

**Issue by apreckler** [Azure/RDS-Templates#452]
After adding a server as a host session, it disappears as a host in the HostPool window when the key validity time has passed to add it as a host.

**Comment by StewartMcL** [comment]
I'm seeing the same also.

**Comment by lintFan** [comment]
@apreckler @StewartMcL  I'm closing this since it is so old so it probably is no longer a problem but feel free to re-open it or file a new github issue if you are still having this problem. If you are still having the problem then please include how you are deploying your session host, for example if you are using an arm template which template is it. Also are you using WVD classic?
