### ISSUE TITLE
Scaling host-pool via Azure Portal does not allowing adding additional desktop users

### ISSUE THREAD

**Issue by bbabcock1990** [Azure/RDS-Templates#457]
When deploying the initial WVD host pool via the Azure using the "Windows Virtual Desktop-Provision a host pool" wizard, deployment will succeed with adding the initial desktop users defined to the host-pool.

When scaling out and re-running the "Windows Virtual Desktop-Provision a host pool" wizard and adding additional desktop users, the users are not added to the host-pool. 

Reviewing the scripts, I see that the Configuration.ps1 script only calls the Script-AddDefaultUsers.ps1 if the deployment includes deploying the very first session-host. If there are additional session host being deployed due to scaling, the Script-AddDefaultUsers.ps1 is not called.

I believe this is a quick fix by adding the Script-AddDefaultUsers.ps1 to the RegisterSessionHost configuration within the Configuration.ps1 file.

**Comment by bbabcock1990** [comment]
This also applies if deploying or scaling host-pools via ARM templates.

**Comment by nakranimohit0** [comment]
@bbabcock1990 
Thank you for raising your concern. We shouldn't add default users for every new session host. Since its per host pool, it would be a duplicate work. If you would like to add additional users, you would have to manually add them as its not supported via ARM templates. You can do that by simply this one command: https://docs.microsoft.com/en-us/powershell/module/windowsvirtualdesktop/add-rdsappgroupuser
