### ISSUE TITLE
Authenticated user should have the Owner/Contributor permissions error while running the createautomationaccount script

### ISSUE THREAD

**Issue by ketkamb** [Azure/RDS-Templates#485]
**4a-WVD-scaling-logicapps **
Hi All ,

I have the Owner access on the subscription but still i am getting below error while running the script 

**error : Authenticated user should have the Owner/Contributor permissions.**    

1. I have 5.1.18362.752 PowerShell version
2. Microsoft AZ PowerShell module is installed.
3.  I have tried with both contributor and owner account still the same error message.
4. Tried with both PowerShell ISE and PowerShell same issue.   

Need your expertise to solve the issue , Thanks in Advance !!

**Comment by ketkamb** [comment]
**4a-WVD-scaling-logicapps **

**Comment by ketkamb** [comment]
Waiting for update

**Comment by monty72** [comment]
Hi, I had the exact same issue and although I have GA and Co-admin on the subscription I had to add Contributor IAM role to my account in the subscription I was trying to deploy to.

**Comment by GrahamHassall** [comment]
I think this might be due to a line of code in the createazurelogicapp.ps1 where it is checking your role assignments
currently on line 191 it uses: 
"$RoleAssignment = (Get-AzRoleAssignment -SignInName $Context.Account)"

but what I have found is that this command does not correctly find your role assignment if you are assigned a role via a group membership.

I fixed this by replacing that line with:
"$RoleAssignment = (Get-AzRoleAssignment -SignInName $Context.Account -ExpandPrincipalGroups)"

This correctly found my group assigned role assignment. Not sure if it would still work if you are directly assigned a role, so you might need to tweak it a little more to use both methods to check role assignment?

**Comment by AAdamCCox** [comment]
I also found this issue when running the script, and worked around it in the same way as @monty72 

I suspect that this is a common IAM scenario (using groups rather than individual permissions is standard practice in many organisations), so a solution incorporating the change mentioned by @GrahamHassall would be welcome

**Comment by viswanadham-k** [comment]
Hi @ketkamb 
If you have still facing issue. Please let me know your availability time then we will sync and assist you with resolved steps.

@monty72 @AAdamCCox Thank you for sharing your thoughts. 

Thanks,

**Comment by RoopChevuri** [comment]
Thanks, we will imbibe this fix in newer version of the script.
