### ISSUE TITLE
Need clarification if the scaling tool works also for the Spring Update

### ISSUE THREAD

**Issue by jhueppauff** [Azure/RDS-Templates#500]
Hi Guys,

I am a bit confused if the Scaling tool works also for the "WVD Spring Update".
The documentation refered in the readme.md is going to a docs page for the fall release. 

thanks

**Comment by RoopChevuri** [comment]
We are currently previewing the tool for Spring update at : https://github.com/nakranimohit0/azure-docs/blob/yammer_private_preview_wvd_scaling/articles/virtual-desktop/set-up-scaling-script.md . Appreciate if you can validate and give feedback in this thread instead of creating a new issue. We will update the public documentation once tool is generally available.

**Comment by nakranimohit0** [comment]
This now generally available, please use this doc: https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script
