### ISSUE TITLE
Works but a failure during peak hours

### ISSUE THREAD

**Issue by FirstGRepo** [Azure/RDS-Templates#514]
I have checked those scripts and also used in the lab scenario.

Following is major drawback;
After the peak hours is over it shuts down all the running VMs and keeps the minimum session host running that were defined earlier regardless of the users logged in. For instance if there are 2 VMs with 2 core each is running. In the setup, 1 session per CPU and 1 minimum session host after peak hours is defined. Now during off peak hours if I have 4 users working on those two VMs, ideally it should not have done anything. But it shuts down the one vm with forcing the sign off of two users.

it should have been like after peak hours if there are more users working, they should have enough cores to work regardless of the minimum host defined.

Regards,
Shyam T

**Comment by nakranimohit0** [comment]
@FirstGRepo 
If you would like to prevent the script from logging off the users, you can set `LimitSecondsToForceLogOffUser` to 0 in the HTTP request body of your Azure Logic App scheduler. This will let the session configuration setting in specified group policies to handle signing off user sessions. Please read more about how it works here: https://aka.ms/wvdscale#how-the-scaling-tool-works

**Comment by FirstGRepo** [comment]
Thanks for the response. I saw it and changed the LimitSecondsToForceLogOffUser to 0. Now it is not forcing users to sign off in off peak hours. However it still need to be scalable to optimize the Available CPUs during peak hours. Suppose I have two host running with 4 CPUs and two users logged in to those two hosts seperately. As the per CPU 1 user is defined, the 2 cpus are running empty during peak hours. is there a way to sign off users from additional host, so they will be signed in back to the available CPUs. if this done we can have one host running serving two users and shut off other one during peak hours.

**Comment by nakranimohit0** [comment]
During peak hours, the tool doesn't not scale in (stop VMs), only scales out (start VMs). We also don't have a way to move active user sessions to a different session hosts without disrupting the user experience. The goal during peak hours is to scale out and maintain the best user experience possible, while the goal during off peak hours is to scale in to minimum possible requirements in order to cut down on cost as much as possible.

However, there is a configuration that might be helpful for your case. By default, the tool sets the host pool load balancer type to breadth first. You can add this new parameter to the request body of the HTTP request in your Logic App Scheduler:
`"SkipUpdateLoadBalancerType": true`
And then update your load balancer type to depth first
This will prevent the scaling tool from changing the load balancer type.
