### ISSUE TITLE
 (Code:InvalidTemplate)

### ISSUE THREAD

**Issue by FFantasma** [Azure/RDS-Templates#627]
I have the return of this error. I wonder if you could help me.
Thanks 
![image](https://user-images.githubusercontent.com/19576265/120246768-9dbfee80-c247-11eb-8e71-a6430373bac8.png)

**Comment by nakranimohit0** [comment]
@FFantasma I'm unable to reproduce this issue. Please share your PowerShell environment info such as `Get-Module` and '$PSVersionTable` AFTER you run the scripts so that I know what module versions were used.

This is what mine looks like

➜  Get-Module

ModuleType Version    Name
---------- -------    ----
Script     2.4.0      Az.Accounts
Script     1.5.2      Az.Automation
Script     3.0.0      Az.DesktopVirtualization
Script     1.5.0      Az.LogicApp
Script     3.2.0      Az.Resources
Manifest   7.0.0.0    Microsoft.PowerShell.Management
Manifest   7.0.0.0    Microsoft.PowerShell.Security
Manifest   7.0.0.0    Microsoft.PowerShell.Utility
Manifest   7.0.0.0    Microsoft.WSMan.Management

➜  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by nakranimohit0** [comment]
Closing because of no response. Please reopen if it occurs again
