### ISSUE TITLE
Azure virtual desktop

### ISSUE THREAD

**Issue by ArslanAyoob** [Azure/RDS-Templates#657]
I need  the guiadance on how to update the Azure Virtual Desktop Image with the latest software using powershell or arm template.

Please share some light.

**Comment by lintFan** [comment]
@ArslanAyoob  Hi, are you using Azure Virtual Desktop (classic) which doesn't support Azure Resource Manager Azure Virtual Desktop objects, or just normal Azure Virtual Desktop (AKA non-classic) ? Basically if you can see a host pool in a resource group in the azure portal then you are using normal AVD.

**Comment by ArslanAyoob** [comment]
@lintFan thanks for coming back to me , I am using azure virtual desktop, but I am not sure, if it is modern or classic, how can I confirm that.

Also is there a way to do it via powershell.

**Comment by ArslanAyoob** [comment]
@lintFan I see itis classic because, it has been deoloyed from the portal, is there a way to upgraded via powershell.

Please share some light.

I am using windows image with  Windows (Windows 10 Enterprise for Virtual Desktops) session hostpool.

**Comment by lintFan** [comment]
@ArslanAyoob just because you deployed AVD via the portal doesn't tell you if it is classic or not. You can run the [get-azwvdhostpool](https://docs.microsoft.com/en-us/powershell/module/az.desktopvirtualization/get-azwvdhostpool?view=azps-6.6.0) powershell command on a resource group that has a hostpool and if it lists the hostpool then you are running the non-classic AVD.

If you are running AVD classic there is a migration tool in public preview [here ](https://docs.microsoft.com/en-us/azure/virtual-desktop/automatic-migration).

**Comment by lintFan** [comment]
Closing due to no response. @ArslanAyoob please feel free to re-open this if you still have a question.
